/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Fafnir.glb 
*/

//jsx of Fafnir.glb generated through npx gltfjsx

//import from libraries
import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

//model variable
const Fafnir = (props) => {
  const group = React.useRef()
  //model location
  const { scene, animations } = useGLTF('./models/Fafnir.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)
  console.log(names);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0.002, 0.015]} scale={0.227}>
          <primitive object={nodes.Controller} />
          <group name="Amber_cube_ring">
            <skinnedMesh castShadow name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube010.skeleton} />
            <skinnedMesh castShadow name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials['Procedural amber']} skeleton={nodes.Cube010_1.skeleton} />
          </group>
          <group name="Amber_RIng">
            <skinnedMesh castShadow name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Fine Gold']} skeleton={nodes.Cylinder.skeleton} />
            <skinnedMesh castShadow name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['Procedural amber']} skeleton={nodes.Cylinder_1.skeleton} />
          </group>
          <skinnedMesh castShadow name="Arm_Band_2" geometry={nodes.Arm_Band_2.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2001" geometry={nodes.Arm_Band_2001.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2001.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2002" geometry={nodes.Arm_Band_2002.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2002.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2003" geometry={nodes.Arm_Band_2003.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2003.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2004" geometry={nodes.Arm_Band_2004.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2004.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2005" geometry={nodes.Arm_Band_2005.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2005.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2006" geometry={nodes.Arm_Band_2006.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2006.skeleton} />
          <skinnedMesh castShadow name="Arm_Band_2007" geometry={nodes.Arm_Band_2007.geometry} material={materials['Fine Gold']} skeleton={nodes.Arm_Band_2007.skeleton} />
          <skinnedMesh castShadow name="B_gum_lp" geometry={nodes.B_gum_lp.geometry} material={materials['B gum']} skeleton={nodes.B_gum_lp.skeleton} />
          <skinnedMesh castShadow name="B_teeth_lp" geometry={nodes.B_teeth_lp.geometry} material={materials.Material} skeleton={nodes.B_teeth_lp.skeleton} />
          <skinnedMesh castShadow name="Bracelet" geometry={nodes.Bracelet.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet.skeleton} />
          <skinnedMesh castShadow name="Bracelet_Ringed" geometry={nodes.Bracelet_Ringed.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet_Ringed.skeleton} />
          <skinnedMesh castShadow name="Bracelet_Ringed001" geometry={nodes.Bracelet_Ringed001.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet_Ringed001.skeleton} />
          <skinnedMesh castShadow name="Bracelet_Ringed002" geometry={nodes.Bracelet_Ringed002.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet_Ringed002.skeleton} />
          <skinnedMesh castShadow name="Bracelet_Ringed003" geometry={nodes.Bracelet_Ringed003.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet_Ringed003.skeleton} />
          <skinnedMesh castShadow name="Bracelet_Ringed004" geometry={nodes.Bracelet_Ringed004.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet_Ringed004.skeleton} />
          <skinnedMesh castShadow name="Bracelet001" geometry={nodes.Bracelet001.geometry} material={materials['Fine Gold']} skeleton={nodes.Bracelet001.skeleton} />
          <group name="Circle">
            <skinnedMesh castShadow name="Circle007_1" geometry={nodes.Circle007_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle007_1.skeleton} />
            <skinnedMesh castShadow name="Circle007_2" geometry={nodes.Circle007_2.geometry} material={materials['Procedural Real Crystals Material.001']} skeleton={nodes.Circle007_2.skeleton} />
          </group>
          <group name="Circle001">
            <skinnedMesh castShadow name="Circle008_1" geometry={nodes.Circle008_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle008_1.skeleton} />
            <skinnedMesh castShadow name="Circle008_2" geometry={nodes.Circle008_2.geometry} material={materials['Procedural Real Crystals Material']} skeleton={nodes.Circle008_2.skeleton} />
          </group>
          <skinnedMesh castShadow name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle002.skeleton} />
          <skinnedMesh castShadow name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle003.skeleton} />
          <skinnedMesh castShadow name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle004.skeleton} />
          <skinnedMesh castShadow name="Circle005" geometry={nodes.Circle005.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle005.skeleton} />
          <group name="Circle006">
            <skinnedMesh castShadow name="Circle014_1" geometry={nodes.Circle014_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle014_1.skeleton} />
            <skinnedMesh castShadow name="Circle014_2" geometry={nodes.Circle014_2.geometry} material={materials['Procedural Real Crystals Material.005']} skeleton={nodes.Circle014_2.skeleton} />
          </group>
          <skinnedMesh castShadow name="Circle007" geometry={nodes.Circle007.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle007.skeleton} />
          <skinnedMesh castShadow name="Circle008" geometry={nodes.Circle008.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle008.skeleton} />
          <skinnedMesh castShadow name="Circle009" geometry={nodes.Circle009.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle009.skeleton} />
          <skinnedMesh castShadow name="Circle010" geometry={nodes.Circle010.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle010.skeleton} />
          <skinnedMesh castShadow name="Circle011" geometry={nodes.Circle011.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle011.skeleton} />
          <skinnedMesh castShadow name="Circle012" geometry={nodes.Circle012.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle012.skeleton} />
          <group name="Circle013">
            <skinnedMesh castShadow name="Circle011_1" geometry={nodes.Circle011_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle011_1.skeleton} />
            <skinnedMesh castShadow name="Circle011_2" geometry={nodes.Circle011_2.geometry} material={materials['Lava Magma 02']} skeleton={nodes.Circle011_2.skeleton} />
          </group>
          <skinnedMesh castShadow name="Circle014" geometry={nodes.Circle014.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle014.skeleton} />
          <skinnedMesh castShadow name="Circle015" geometry={nodes.Circle015.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle015.skeleton} />
          <skinnedMesh castShadow name="Circle016" geometry={nodes.Circle016.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle016.skeleton} />
          <skinnedMesh castShadow name="Circle017" geometry={nodes.Circle017.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle017.skeleton} />
          <skinnedMesh castShadow name="Circle018" geometry={nodes.Circle018.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle018.skeleton} />
          <skinnedMesh castShadow name="Circle019" geometry={nodes.Circle019.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle019.skeleton} />
          <skinnedMesh castShadow name="Circle020" geometry={nodes.Circle020.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle020.skeleton} />
          <skinnedMesh castShadow name="Circle021" geometry={nodes.Circle021.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle021.skeleton} />
          <skinnedMesh castShadow name="Circle022" geometry={nodes.Circle022.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle022.skeleton} />
          <skinnedMesh castShadow name="Circle023" geometry={nodes.Circle023.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle023.skeleton} />
          <skinnedMesh castShadow name="Circle024" geometry={nodes.Circle024.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle024.skeleton} />
          <group name="Circle025">
            <skinnedMesh castShadow name="Circle049" geometry={nodes.Circle049.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle049.skeleton} />
            <skinnedMesh castShadow name="Circle049_1" geometry={nodes.Circle049_1.geometry} material={materials['Procedural Real Crystals Material.006']} skeleton={nodes.Circle049_1.skeleton} />
          </group>
          <skinnedMesh castShadow name="Circle026" geometry={nodes.Circle026.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle026.skeleton} />
          <group name="Circle027">
            <skinnedMesh castShadow name="Circle050" geometry={nodes.Circle050.geometry} material={materials['Procedural Real Crystals Material']} skeleton={nodes.Circle050.skeleton} />
            <skinnedMesh castShadow name="Circle050_1" geometry={nodes.Circle050_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle050_1.skeleton} />
          </group>
          <skinnedMesh castShadow name="Circle028" geometry={nodes.Circle028.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle028.skeleton} />
          <skinnedMesh castShadow name="Circle029" geometry={nodes.Circle029.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle029.skeleton} />
          <group name="Claw_Ring">
            <skinnedMesh castShadow name="Circle010_1" geometry={nodes.Circle010_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle010_1.skeleton} />
            <skinnedMesh castShadow name="Circle010_2" geometry={nodes.Circle010_2.geometry} material={materials['Procedural Real Crystals Material.004']} skeleton={nodes.Circle010_2.skeleton} />
          </group>
          <group name="Claw_Ring001">
            <skinnedMesh castShadow name="Circle029_1" geometry={nodes.Circle029_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle029_1.skeleton} />
            <skinnedMesh castShadow name="Circle029_2" geometry={nodes.Circle029_2.geometry} material={materials['Procedural Real Crystals Material.004']} skeleton={nodes.Circle029_2.skeleton} />
          </group>
          <skinnedMesh castShadow name="Coil_Ring" geometry={nodes.Coil_Ring.geometry} material={materials['Fine Gold']} skeleton={nodes.Coil_Ring.skeleton} />
          <group name="Cube">
            <skinnedMesh castShadow name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube005.skeleton} />
            <skinnedMesh castShadow name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['Red Crystal']} skeleton={nodes.Cube005_1.skeleton} />
          </group>
          <group name="Cube001">
            <skinnedMesh castShadow name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Procedural Real Crystals Material.002']} skeleton={nodes.Cube008.skeleton} />
            <skinnedMesh castShadow name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube008_1.skeleton} />
          </group>
          <group name="Cube002">
            <skinnedMesh castShadow name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Procedural amber']} skeleton={nodes.Cube006.skeleton} />
            <skinnedMesh castShadow name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube006_1.skeleton} />
          </group>
          <group name="Diamond_Ring">
            <skinnedMesh castShadow name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh castShadow name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Crystal Glass']} skeleton={nodes.Cube002_2.skeleton} />
          </group>
          <skinnedMesh castShadow name="eyes_lp" geometry={nodes.eyes_lp.geometry} material={materials['Fine Gold']} skeleton={nodes.eyes_lp.skeleton} />
          <skinnedMesh castShadow name="F_nail_lp" geometry={nodes.F_nail_lp.geometry} material={materials['Material.001']} skeleton={nodes.F_nail_lp.skeleton} />
          <skinnedMesh castShadow name="lp" geometry={nodes.lp.geometry} material={materials['Faf lp']} skeleton={nodes.lp.skeleton} />
          <skinnedMesh castShadow name="Plate" geometry={nodes.Plate.geometry} material={materials['Fine Gold']} skeleton={nodes.Plate.skeleton} />
          <group name="Ruby_Bracelet">
            <skinnedMesh castShadow name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle003_1.skeleton} />
            <skinnedMesh castShadow name="Circle003_2" geometry={nodes.Circle003_2.geometry} material={materials['Red Crystal']} skeleton={nodes.Circle003_2.skeleton} />
          </group>
          <group name="Ruby_Bracelet001">
            <skinnedMesh castShadow name="Circle012_1" geometry={nodes.Circle012_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle012_1.skeleton} />
            <skinnedMesh castShadow name="Circle012_2" geometry={nodes.Circle012_2.geometry} material={materials['Red Crystal']} skeleton={nodes.Circle012_2.skeleton} />
          </group>
          <group name="Ruby_Ring">
            <skinnedMesh castShadow name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Cube_1.skeleton} />
            <skinnedMesh castShadow name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Red Crystal']} skeleton={nodes.Cube_2.skeleton} />
          </group>
          <group name="Sapphire_Ring">
            <skinnedMesh castShadow name="Circle015_1" geometry={nodes.Circle015_1.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle015_1.skeleton} />
            <skinnedMesh castShadow name="Circle015_2" geometry={nodes.Circle015_2.geometry} material={materials['Procedural Real Crystals Material.003']} skeleton={nodes.Circle015_2.skeleton} />
          </group>
          <group name="Sapphire_Ring001">
            <skinnedMesh castShadow name="Circle035" geometry={nodes.Circle035.geometry} material={materials['Fine Gold']} skeleton={nodes.Circle035.skeleton} />
            <skinnedMesh castShadow name="Circle035_1" geometry={nodes.Circle035_1.geometry} material={materials['Procedural Real Crystals Material.001']} skeleton={nodes.Circle035_1.skeleton} />
          </group>
          <skinnedMesh castShadow name="Staunching_ring" geometry={nodes.Staunching_ring.geometry} material={materials['Fine Gold']} skeleton={nodes.Staunching_ring.skeleton} />
          <skinnedMesh castShadow name="Staunching_ring001" geometry={nodes.Staunching_ring001.geometry} material={materials['Fine Gold']} skeleton={nodes.Staunching_ring001.skeleton} />
          <skinnedMesh castShadow name="Staunching_ring002" geometry={nodes.Staunching_ring002.geometry} material={materials['Fine Gold']} skeleton={nodes.Staunching_ring002.skeleton} />
          <skinnedMesh castShadow name="T_nail_lp" geometry={nodes.T_nail_lp.geometry} material={materials['Material.002']} skeleton={nodes.T_nail_lp.skeleton} />
          <skinnedMesh castShadow name="thorn_ring" geometry={nodes.thorn_ring.geometry} material={materials['Fine Gold']} skeleton={nodes.thorn_ring.skeleton} />
          <skinnedMesh castShadow name="thorn_ring001" geometry={nodes.thorn_ring001.geometry} material={materials['Fine Gold']} skeleton={nodes.thorn_ring001.skeleton} />
          <skinnedMesh castShadow name="thorn_ring002" geometry={nodes.thorn_ring002.geometry} material={materials['Fine Gold']} skeleton={nodes.thorn_ring002.skeleton} />
          <skinnedMesh castShadow name="tongue_lp" geometry={nodes.tongue_lp.geometry} material={materials.Tongue} skeleton={nodes.tongue_lp.skeleton} />
          <skinnedMesh castShadow name="U_gum_lp" geometry={nodes.U_gum_lp.geometry} material={materials['U gum']} skeleton={nodes.U_gum_lp.skeleton} />
          <skinnedMesh castShadow name="U_teeth_lp" geometry={nodes.U_teeth_lp.geometry} material={materials['Material.003']} skeleton={nodes.U_teeth_lp.skeleton} />
        </group>
      </group>
    </group>
  )
};

export default Fafnir;

useGLTF.preload('./models/Fafnir.glb');
